image: anapsix/alpine-java:8_jdk

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - apk update
    - apk add less zip curl
  script: 
    - ./build.sh
  artifacts:
    paths:
      - ./build/x86_64-darwin/Chemaria_x86_64-darwin.zip
      - ./build/x86_64-linux/Chemaria_x86_64-linux.zip
      - ./build/x86_64-win32/Chemaria_x86_64-win32.zip

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apk update
    - apk add zip curl
  script:
    - ./deploy.sh
