image: openjdk:11

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - apt update
    - apt install -y less zip curl
  script:
    - bash ./build.sh
  artifacts:
    paths:
      - ./build/x86_64-darwin/Chemaria_x86_64-darwin.zip
      - ./build/x86_64-linux/Chemaria_x86_64-linux.zip
      - ./build/x86_64-win32/Chemaria_x86_64-win32.zip
deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apt update
    - apt install -y zip curl
  script:
    - bash ./deploy.sh
