image: ubuntu:latest

before_script:
  - apt update
  - apt install -y software-properties-common
  - add-apt-repository ppa:webupd8team/java
  - apt update
  - echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  - echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
  - apt install -y oracle-java8-installer
  - apt install -y less zip curl

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - ./build.sh
  artifacts:
    paths:
      - ./build/x86_64-darwin/Chemaria_x86_64-darwin.zip
      - ./build/x86_64-linux/Chemaria_x86_64-linux.zip
      - ./build/x86_64-darwin/Chemaria_x86_64-win32.zip

deploy:
  stage: deploy
  script:
    - ./deploy.sh
