image: ubuntu:latest

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - apt update
    - apt install -y software-properties-common
    - echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
    - echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
    - apt update
    - echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
    - echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
    - apt install -y oracle-java8-installer
    - apt install -y less zip curl
  script: 
    - ./build.sh
  artifacts:
    paths:
      - ./build/x86_64-darwin/Chemaria_x86_64-darwin.zip
      - ./build/x86_64-linux/Chemaria_x86_64-linux.zip
      - ./build/x86_64-win32/Chemaria_x86_64-win32.zip

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apt update
    - apt install -y zip curl
  script:
    - ./deploy.sh
