local helpers = require "modules.helpers"
local message_constants = require "modules.constants.messages"

-------------
-- Helpers --
-------------

local show_proxy

function show_proxy(self, proxy)
	if self.current_proxy then
		msg.post(self.current_proxy, "unload")
	end
	msg.post(proxy, "async_load")
end

-----------------
-- End Helpers --
-----------------

----------------------
-- Defold functions --
----------------------

function init(self)
	helpers.init_config_data()

	helpers.set_resolution(nil, helpers.get_config_data("fullscreen"))
	helpers.load_cursor("default")

	helpers.apply_config()

	msg.post(".", "acquire_input_focus")
	show_proxy(self, "#main_menu_proxy")
end

function on_message(self, message_id, message, sender)
	if message_id == message_constants.PROXY_LOADED then
		self.current_proxy = sender
		msg.post(sender, "enable")
	elseif message_id == message_constants.SWITCH_PROXY then
		show_proxy(self, message.switch_to)
	end
end

--------------------------
-- End Defold functions --
--------------------------