-------------
-- Helpers --
-------------

local show

function show(self, proxy)
	if self.currentProxy then
		msg.post(self.currentProxy, "unload")
	end
	msg.post(proxy, "async_load")
end

-----------------
-- End Helpers --
-----------------


----------------------
-- Defold functions --
----------------------

function init(self)
	defos.set_fullscreen(true)
	msg.post(".", "acquire_input_focus")
	show(self, "#mainmenuproxy")
	msg.post("@render:", "clear_color", { color = vmath.vector4(0.15, 0.15, 0.15, 1.0) })
end

function on_message(self, messageId, message, sender)
	if messageId == hash("proxy_loaded") then
		self.currentProxy = sender
		msg.post(sender, "enable")
	elseif messageId == hash("switch_proxy") then
		show(self, message.switchTo)
	end
end

--------------------------
-- End Defold functions --
--------------------------