local helpers = require "modules.helpers"
local message_constants = require "modules.constants.messages"

-------------
-- Helpers --
-------------

local show_proxy

function show_proxy(self, proxy)
	if self.currentProxy then
		msg.post(self.currentProxy, "unload")
	end
	msg.post(proxy, "async_load")
end

-----------------
-- End Helpers --
-----------------

----------------------
-- Defold functions --
----------------------

function init(self)
	helpers.apply_config()

	helpers.init_config_data()
	screen_size = helpers.get_config_data("SCREEN_SIZE")
	defos.set_cursor_visible(false)
	msg.post(".", "acquire_input_focus")
	show_proxy(self, "#main_menu_proxy")
end

function on_message(self, messageId, message, sender)
	if messageId == message_constants.PROXY_LOADED then
		self.currentProxy = sender
		msg.post(sender, "enable")
	elseif messageId == message_constants.SWITCH_PROXY then
		show_proxy(self, message.switchTo)
	end
end

--------------------------
-- End Defold functions --
--------------------------