function init(self)
	msg.post(".", "acquire_input_focus")
	self.game_mode = "play"
end

function on_input(self, actionId, action)
	if self.game_mode == "play" then
		if actionId == hash("left") then
			send_player_action(actionId, action)
		elseif actionId == hash("right") then
			send_player_action(actionId, action)
		elseif actionId == hash("jump") then
			send_player_action(actionId, action)
		elseif actionId == hash("quit") and action.pressed then
			quit_game()
		elseif actionId == hash("left_click") then
			send_gui_action(actionId, action)
			send_player_action(actionId, action)
		elseif actionId == hash("right_click") then
			send_player_action(actionId, action)
		end
	end
	if actionId == hash("toggle_profile") and action.pressed then
		msg.post("@system:", "toggle_profile")
	elseif actionId == hash("toggle_fullscreen") and action.pressed then
		defos.toggle_fullscreen()
	end
end

function quit_game()
	msg.post("@system:", "exit", { code = 0 })
end

function send_player_action(actionId, action)
	msg.post("/player#player_script", actionId, action)
end

function send_gui_action(actionId, action)
	msg.post("/ui#ui", actionId, action)
end