function init(self)
	msg.post(".", "acquire_input_focus")
	self.game_mode = "play"
end

function on_input(self, actionId, action)
	if self.game_mode == "play" then
		if actionId == hash("up") then
			send_player_action("up", action)
		elseif actionId == hash("down") then
			send_player_action("down", action)
		elseif actionId == hash("left") then
			send_player_action("left", action)
		elseif actionId == hash("right") then
			send_player_action("right", action)
		elseif actionId == hash("jump") then
			send_player_action("jump", action)
		elseif actionId == hash("quit") and action.pressed then
			quit_game()
		end
	elseif actionId == hash("toggle_profiler") then
		msg.post("@system:", "toggle_profile")
	end
end

function quit_game()
	msg.post("@system:", "exit", { code = 0 })
end

function send_player_action(actionId, action)
	msg.post("/player#player_script", actionId, action)
end