local gooey = require "gooey.gooey"
local theme = require "main.ui.theme"
local world_constants = require "modules.constants.world"

-------------
-- Helpers --
-------------

local function button_handler(button, handler)
	if button.released_now then
		handler()
	end
end

-----------------
-- End Helpers --
-----------------

----------------------
-- Defold functions --
----------------------

function init(self)
	msg.post("@render:", "clear_color", { color = vmath.vector4(0.15, 0.15, 0.15, 1.0) })
	gooey.acquire_input()
	world_constants.SCALE = nil
end

function on_input(self, actionId, action)
	if actionId == hash("quit") and action.released then
		msg.post("@system:", "exit", { code = 0 })
	else
		theme.button("new_game", actionId, action, function(button)
			button_handler(button, function()
				msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#new_game_menu_proxy" })
			end)
		end)

		theme.button("load_game", actionId, action, function(button)
			button_handler(button, function()
				msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#load_game_menu_proxy" })
			end)
		end)

		theme.button("settings", actionId, action, function(button)
			button_handler(button, function()
				msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#settings_menu_proxy" })
			end)
		end)

		theme.button("exit_game", actionId, action, function(button)
			button_handler(button, function()
				msg.post("@system:", "exit", { code = 0 })
			end)
		end)
	end
end

function final(self)
	gooey.release_input()
end

--------------------------
-- End Defold functions --
--------------------------