local INVENTORY = {}

INVENTORY.INVENTORY_SIZE = {
	rows = 3,
	rowSize = 10
}
INVENTORY.INVENTORY_MAX_SLOTS = INVENTORY.INVENTORY_SIZE.rows * INVENTORY.INVENTORY_SIZE.rowSize
INVENTORY.INVENTORY_SELECTED_COLOR = vmath.vector4(0.47, 0.9, 0.2, 1)
INVENTORY.INVENTORY_UNSELECTED_COLOR = vmath.vector4(1, 1, 1, 1)

return INVENTORY