local PLAYER = {}

PLAYER.PLAYER_HEIGHT = 60
PLAYER.PLAYER_JUMP_FORCE = 800
PLAYER.PLAYER_LINEAR_DAMPING = 0.9
PLAYER.PLAYER_MAX_VELOCITY = 600
PLAYER.PLAYER_VELOCITY = vmath.vector3(300, 0, 0)
PLAYER.PLAYER_WIDTH = 36
PLAYER.PLAYER_BASE_MINING_INTERVAL = 0.5
PLAYER.PLAYER_BASE_PLACING_INTERVAL = 0.1

return PLAYER