local PLAYER = {}

PLAYER.BASE_MINING_DISTANCE = 200
PLAYER.BASE_PLACING_DISTANCE = 400
PLAYER.BASE_MINING_INTERVAL = 0.25
PLAYER.BASE_PLACING_INTERVAL = 0.1
PLAYER.BASE_MINING_POWER = 1
PLAYER.HEIGHT = 60
PLAYER.JUMP_FORCE = 800
PLAYER.MAX_VELOCITY = 600
PLAYER.VELOCITY = vmath.vector3(300, 0, 0)
PLAYER.WIDTH = 36

return PLAYER