local WORLD = {}

WORLD.BLOCK_SIZE = 24
WORLD.WORLD_DIMENSIONS = vmath.vector3(10, 10, 0)
WORLD.CHUNK_SIZE = 12
WORLD.RENDER_DISTANCE = vmath.vector3(5, 3, 0)
WORLD.SEED = nil

WORLD.SMALL = 1
WORLD.MEDIUM = 2
WORLD.LARGE = 3

return WORLD