local gooey = require "gooey.gooey"
local input_constants = require "modules.constants.input"
local theme = require "main.ui.theme"
local world_constants = require "modules.constants.world"

local SCOPED_SELF

-------------
-- Helpers --
-------------

local button_handler
local radio_handler
local exit_to_main_menu

function button_handler(button, handler)
	if button.released_now then
		handler()
	end
end

function radio_handler(radio, handler)
	if radio.released_now then
		handler()
	end
end

function exit_to_main_menu(self)
	msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#main_menu_proxy" })
end

-----------------
-- End Helpers --
-----------------

----------------------
-- Defold functions --
----------------------

function init(self)
	SCOPED_SELF = self

	gooey.acquire_input()
end

function on_input(self, actionId, action)
	if actionId == input_constants.QUIT and action.released then
		exit_to_main_menu(self)
	end

	theme.button("return_to_main_menu", actionId, action, function(button)
		button_handler(button, function()
			exit_to_main_menu(SCOPED_SELF)
		end)
	end)

	theme.button("create_world", actionId, action, function(button)
		button_handler(button, function()
			if world_constants.SCALE then
				msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#world_proxy" })
			end
		end)
	end)

	theme.radiogroup("scale_group", actionId, action, function(groupId, actionId, action)
		theme.radio("small_radio", groupId, actionId, action, function(radio)
			radio_handler(radio, function()
				world_constants.SCALE = "SMALL"
			end)
		end)

		theme.radio("medium_radio", groupId, actionId, action, function(radio)
			radio_handler(radio, function()
				world_constants.SCALE = "MEDIUM"
			end)
		end)

		theme.radio("large_radio", groupId, actionId, action, function(radio)
			radio_handler(radio, function()
				world_constants.SCALE = "LARGE"
			end)
		end)
	end)
end

function final(self)
	gooey.release_input()
end

--------------------------
-- End Defold functions --
--------------------------