local gooey = require "gooey.gooey"
local theme = require "main.main_menu.main_menu_theme.theme"

-------------
-- Helpers --
-------------

local function button_handler(button, handler)
	if button.released_now then
		handler()
	end
end

-----------------
-- End Helpers --
-----------------

----------------------
-- Defold functions --
----------------------

function init(self)
	gooey.acquire_input()
end

function on_input(self, actionId, action)
	if actionId == hash("quit") and action.released then
		msg.post("@system:", "exit", { code = 0 })
	else
		theme.button("new_game", actionId, action, function(button)
			button_handler(button, function() 
				msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#worldproxy" })
			end)
		end)

		theme.button("load_game", actionId, action, function(button)
			button_handler(button, function() 
				print("Load game...")
			end)
		end)

		theme.button("settings", actionId, action, function(button)
			button_handler(button, function() 
				print("Settings...")
			end)
		end)

		theme.button("exit_game", actionId, action, function(button)
			button_handler(button, function() 
				msg.post("@system:", "exit", { code = 0 })
			end)
		end)
	end
end

--------------------------
-- End Defold functions --
--------------------------