local gooey = require "gooey.gooey"
local theme = require "main.menus.main_menu.main_menu_theme.theme"

-------------
-- Helpers --
-------------

local function button_handler(button, handler)
	if button.released_now then
		handler()
	end
end

-----------------
-- End Helpers --
-----------------

----------------------
-- Defold functions --
----------------------

function init(self)
	gooey.acquire_input()
end

function on_input(self, actionId, action)
	theme.button("return_to_main_menu", actionId, action, function(button)
		button_handler(button, function()
			msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#main_menu_proxy" })
		end)
	end)
end

function final(self)
	gooey.release_input()
end

--------------------------
-- End Defold functions --
--------------------------