local config = require "modules.config"
local gooey = require "gooey.gooey"
local input_constants = require "modules.constants.input"
local theme = require "main.menus.theme.theme"

-------------
-- Helpers --
-------------

local button_handler
local exit_to_main_menu

function button_handler(button, handler)
	if button.released_now then
		handler()
	end
end

function exit_to_main_menu()
	zoomLevel = tonumber(gui.get_text(gui.get_node("zoom_input/text")))
	if zoomLevel then
		print("zoom", zoomLevel)
		config.CAMERA_ZOOM_LEVEL.zoom = zoomLevel
	end
	msg.post("main:/loader#loader", "switch_proxy", { switchTo = "#main_menu_proxy" })
end

-----------------
-- End Helpers --
-----------------

----------------------
-- Defold functions --
----------------------

function init(self)
	gooey.acquire_input()
	gui.set_text(gui.get_node("zoom_input/text"), tostring(config.CAMERA_ZOOM_LEVEL.zoom))
end

function on_input(self, actionId, action)
	if actionId == input_constants.QUIT and action.released then
		exit_to_main_menu()
	end

	theme.button("return_to_main_menu", actionId, action, function(button)
		button_handler(button, function()
			exit_to_main_menu()
		end)
	end)

	theme.input("zoom_input", gui.KEYBOARD_TYPE_NUMBER_PAD, actionId, action, {
		max_length = 4,
		empty_text = "Enter zoom level...",
		allowed_characters = "[%d%.]"
	})
end

function final(self)
	gooey.release_input()
end

--------------------------
-- End Defold functions --
--------------------------